### ISSUE TITLE
It is not possible to add equipment to cargo net boxes

### ISSUE THREAD

**Issue by daWaschbaer** [ArmaAchilles/Achilles#492] opened 2019-06-17 19:13 UTC
**Arma 3 Version:** `1.92` (stable)  
**CBA Version:** `3.11.2` (stable)  
**Achilles Version:** `1.2.1` (stable)  

**Mods:**
```
- CBA_A3
- Achilles
```
**Description:**
- As a Zeus, it is not possible to add weapons or any kind of equipment to Cargo Net Boxes, nor it is possible to see it's current content.
- The only exceptions are medkits, rangefinder and toolkits

**Steps to reproduce:**
- Create a multiplayer game with one of the official Zeus Multiplayer Scenarios
- Select the Game Master role and start the mission
- Create all necessary respawn positions in order to be able to place objects, units, etc.
- Go to Units -> Empty -> Supplies -> Storage and spawn one of the Cargo Net Boxes
- Double click on the box in order to see it's content and try to add any weapon or equipment to the box
- Once you're finished confirm the box's content using the "OK" button
- Double click the box again to see that the added content is not in the box
- Alternatively try to access the box as a remote controlled unit to see that the content is not there (or have another player try to take a look inside the box)

**Where did the issue occur?**
- Environment: Self-Hosted Multiplayer as a Zeus
- Mission: Tested in 
"Zeus 16+2 Master Malden (Nato)"
"Zeus 48+2 Master Malden"
"Zeus 16+2 Master Altis (Nato)"
"Zeus 16+2 Master Altis"

It was possible to reproduce this problem with only CBA_A3 and Achilles active and with other players (not the host) being Zeus

**Comment by synixebrett** [comment] 2019-06-18 03:44
Duplicate of #487

**Closed** 2019-06-18 16:33 UTC
Labels: bug, duplicate, priority/high
