### ISSUE TITLE
Feature Request: Dispersion option in Artillery Fire Mission

### ISSUE THREAD

**Issue by stafmoony** [ArmaAchilles/Achilles#313] opened 2018-05-19 16:54 UTC
Hey, I wonder if its possible to add a Dispersion option to the Artillery Fire Mission.

I usually use the module to scare my player, put them under pressure or give them a slight hint to move there butts. However, I really dislike the morter shots hitting basically the same spot if you e.g. send 5 shots by 3 mortar. They all hit in like a 5 or 10 meter radius. 
While this might be fine for some it would be nice to have the option to set the radius to like 50 or so.

**Comment by oOKexOo** [comment] 2018-05-19 22:38
Duplicate of #133.

**Closed by oOKexOo** 2018-05-19 22:38 UTC
Labels: duplicate
