### ISSUE TITLE
SQF Execute Code Module - No Unit Spawns

### ISSUE THREAD

**Issue by streaker03** [ArmaAchilles/Achilles#185] opened 2017-11-20 22:02 UTC
**Arma 3 Version:** `x.xx` (stable / rc / dev)  
**CBA Version:** `3.x.x` (stable / dev + commit hash)  
**AresModAchillesExpansion Version:** `x.x.x` (stable / dev + commit hash)  

**Mods:**
```
- JSRS
- Blastcore Edited (standalone version)
- Enhanced Movement
- VSM All-In-One Collection
- ShackTack
- Advanced Urban Rappeling
- The other rappeling mod made by the same guy as ^^
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- Copied mission sqf then later pasted it back in and everything spawned except for A. I. with a few exceptions such as turrets

**Steps to reproduce:**
- Copy Mission SQF
- Execute Code Module with the sqf pasted

**Where did the issue occur?**
- My personal dedicated server but I dont think it would work otherwise

**RPT log file:**
- SQF I USED https://pastebin.com/Jnd7Lbfq
- RPT FILE https://pastebin.com/Ew923V0S

**Comment by CreepPork** [comment] 2017-11-29 17:54
This seems to be a weird issue. I cannot replicate the issue and it could have happened due to multiple factors, depending on the conditions. I'm moving this issue back to the backlog for further investigation.

**Comment by Magik4** [comment] 2017-12-24 19:30
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0` (stable)  
**AresModAchillesExpansion Version:** `0.0.9c` (stable)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- I experience the same problem when executing my .sqf (To be clear - I use the `Mode: Local`).
- There should be many CSAT tanks and soldiers near *Agios Dionysios*. There are none.

**Steps to reproduce:**
- Copy my [SQF file](https://gist.github.com/Magik4/13a0a06588215807e4df9b98eb7d8eb5).
- Use the Execute Code Module.
- Paste the code.
- Press OK.
- BONUS: Add editable Objects into Zeus as they never add themselves automagically.

**Where did the issue occur?**
- Self-Hosted Multiplayer,
- Client on Hosted Multiplayer

**Additional info:**
- No idea what causes the problem. It happens pretty random.

**Files:**
- [RPT log file](https://gist.github.com/Magik4/0b52b8e72087bc7504cb821044173c0f)

**Comment by CreepPork** [comment] 2018-03-11 23:30
There is an issue in the code if a unit has gone missing it replaces it with a question mark which then breaks it on execution.

**Closed** 2018-06-10 18:39 UTC
Labels: bug, priority/low
