### ISSUE TITLE
Attribute window get opened twice for promoted curators

### ISSUE THREAD

**Issue by shukari** [ArmaAchilles/Achilles#404] opened 2018-10-15 11:00 UTC
**Arma 3 Version:** stable
**CBA Version:** stable 
**Achilles Version:** stable

**Mods:**
```
- CBA_A3
- Achilles
```

**Description:**
If you create a curator during the mission with this snippet from your assignZeus module
https://github.com/ArmaAchilles/Achilles/blob/a4b0525a92e2d180afa92e51e71598572d264193/%40AresModAchillesExpansion/addons/modules_f_achilles/Zeus/functions/fn_ZeusAssignZeus.sqf#L28-L35
you get double guis for any action.

**Steps to reproduce:**
- create a curator during the mission and assign it to you
- double click a group
- a gui opens... click ok
- a gui opens... click ok (only changes at this gui will be assigend)
- end

**Where did the issue occur?**
- Dedicated

**Comment by oOKexOo** [comment] 2018-10-16 19:41
Yes, you might have noticed that the issue was recently discussed on Discord, but I forgot to create an issue for it here. The issue is a general behavior of curator modules created on the fly and independent of Achilles. A possible workaround could be to delete the duplicate curator event handlers manually.

**Comment by oOKexOo** [comment] 2018-12-08 19:07
It could be that BI's revision to module initialization in `1.86` fixed that issue by accident. Is it true?

**Comment by oOKexOo** [comment] 2019-01-04 02:14
Closed as outdated. If this issue is still around nonetheless, let us know.

**Closed by oOKexOo** 2019-01-04 02:14 UTC
Labels: BIS fault, bug, priority/medium
